name: angular
on:
  push:
    branches:
      - main
    paths:
      - "angular/**"
  pull_request:
    branches:
      - main
    paths:
      - "angular/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build angular
